# Generated by Django 3.2.6 on 2021-08-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows', '0003_alter_show_network'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ('title',)},
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
